### ISSUE TITLE
Moving to a GitHub CMS

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#10]
Here are my requirements for blogging platforms:

- Should be easy and fast to update - no long or flaky build process
- Should store images easily - as simple as a paste from my clipboard - anything else is unnecessary friction
- Should be easily editable from mobile
- (optional) should support comment system and different layout formats
- (optional) wysiwyg markdown based editing - no funky blocks with lots of lockin

After thinking through local markdown, GraphCMS, Notion, Strapi, Directus, and so on, I've finally settled on using GitHub as a CMS.

I've long admired the OneGraph approach to blogging:

- https://github.com/OneGraph/onegraph-blog
- https://github.com/OneGraph/onegraph-changelog/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+label%3APublish

However their use of Relay is a bit too high overhead for me. So I built my own using just the GitHub REST API.

The primary problem with GH's API is that it rate limits at 5000 requests an hour, which is dicey for a high traffic blog. So either you prerender at build, or you cache on request (we can also cache on build). Netlify's [On Demand Builders](https://docs.netlify.com/configure-builds/on-demand-builders/) are a partial solution to this - partial because content updates will not be respected. I think this is an acceptable tradeoff for all the other functionality github as a cms offers.

The PR for doing this is available here: https://github.com/sw-yx/swyxkit/pull/9

**Comment by sw-yx** [comment]
this is a test comment

**Comment by sw-yx** [comment]
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti fugiat quod non ipsum perspiciatis voluptatum pariatur explicabo enim, suscipit sapiente, quo perferendis amet sint voluptates. Quibusdam ullam voluptatibus expedita repudiandae quos tenetur, modi eligendi eos. Sit cum unde dolor assumenda error, suscipit earum, corrupti molestias vero quae incidunt enim aspernatur magni inventore reprehenderit esse rerum quas, at itaque? Autem repellendus cupiditate natus vero inventore sit! Excepturi expedita optio in! Sapiente rerum fuga dignissimos odit iure laboriosam earum non dolores obcaecati repellendus ipsum minus enim eum et, totam facere? Doloribus autem sed magni nobis aspernatur nulla officiis impedit nostrum obcaecati assumenda!

**Comment by sahilsharma011** [comment]
How long does it take for new reactions to come on the netlify rendered blog?

**Comment by sahilsharma011** [comment]
So I can't see my comment edits on the rendered blog because I think that is due to the edge caching you mentioned on netlify?
But before opening up the netlify site, I added some reactions to your comments and even those were not visible for me when I visited the site for the first time.

**Comment by sw-yx** [comment]
yeah because i cache the api response for 1min-1hr.

i think if you retry on incognito it will work

i have not implemented reactions on comments yet… pr welcome for that one haha

**Comment by sw-yx** [comment]
test comments for testing markdown rendering in comments


## Snarkdown

![snarkdown](http://emojipop.net/data/images/emoji_set_77.png)

*[Snarkdown](http://github.com/developit/snarkdown)* is __easy__ to `use`!

Here's an [**important** anchor link](#example).

Two newlines creates a line break.

Or, end a line with two spaces.  
Just like that!

Code & Poetry
-------------

    You can also indent
    blocks to display
    code or poetry.
    
    Indented code/poetry blocks  
    can be hard-wrapped.

**Or, wrap your code in three backticks:**

```
function codeBlocks() {
    return 'Can be inser
}
```


### Block Quotes

> You can insert quotes by
> preceeding each line with `>`.
>
> Blockquotes can also contain line  
> breaks.


## Lists

- Unordered
* Lists
+ Of mixed type

1. Ordered
2. Lists
4. Numbers are ignored

**Comment by lawrencecchen** [comment]
noice.

**Comment by sw-yx** [comment]
i fixed the buggy snarkdown rendering with the string replace recommended here https://github.com/developit/snarkdown/issues/69

**Comment by avblackwell** [comment]
This is really cool!

**Comment by Klerpson** [comment]
wow is amazing

**Comment by RyKilleen** [comment]
Curious to see if it supports syntax highlighting for a given language

```js
function veryCool() {
   console.log('awesome approach!')
}
```

**Comment by sw-yx** [comment]
haha no, because this is all rendered clientside and i didnt want to add extra js weight, but you should be able to add highlight.js easily

**Comment by pi43r** [comment]
<script>alert('this should not happen');</script>

**Comment by miedzikd** [comment]
<script>
  import FeatureCard from '$lib/../components/FeatureCard.svelte';
</script>

### Hello

It will be awesome if this can work ;)

<FeatureCard title="Dynamic Feature" stringData="It will be so cool to see this on your website" />

**Comment by pi43r** [comment]
> <script> import FeatureCard from '$lib/../components/FeatureCard.svelte'; </script>
> ### Hello
> 
> It will be awesome if this can work ;)

It would be a major security flaw if this would work ;)
