### ISSUE TITLE
Question about ## suffixes for header

### ISSUE THREAD

**Issue by georgeoffley** [sw-yx/swyxkit#152]
I'm just curious if [this](https://github.com/sw-yx/swyxkit/blob/093277297f9fdea9ffbfb49d7a6fd697c43ee4c7/src/tailwind.css#L122) was a design decision or if there's a specific reason for appending `##` at the beginning of header tags.

**Comment by sw-yx** [comment]
pure design decision, remove it if you like :)

i just like to make it easy to see what level the heading is at
