### ISSUE TITLE
website has 500 status code after deployment to netlify

### ISSUE THREAD

**Issue by balthazarpierre** [sw-yx/swyxkit#156]
The website is always in 500 status code after trying to deploy to netlify with my own website parameters in siteConfig.js
It doesn't seem to come from github token since I have no 401 in function logs. 

Do have any ideas where it could come from as the error is not particularly explicit ? 

![Capture d’écran 2023-01-06 à 14 18 18](https://user-images.githubusercontent.com/122002069/211020473-07efe165-c7c8-4a01-8653-bea0538e5f5c.png)

**Comment by sw-yx** [comment]
i have no idea but let me know if you figured it out!
