### ISSUE TITLE
Overflow causing horizontal scrolling

### ISSUE THREAD

**Issue by TheRyanFurrer** [sw-yx/swyxkit#16]
When viewing the site on my iPhone 13 Mini I noticed that elements like tables and the comments are causing horizontal overflow, thus creating a horizontal scrollbar. 

Confirms it renders the same same issue on Safari, Chrome, and Firefox. 

![124E53A1-CDB2-4F4F-A8BD-CF0166417271](https://user-images.githubusercontent.com/40150036/149645844-7f551d98-1b80-493d-a331-cd5cb1415a5d.png)

**Comment by sw-yx** [comment]
thank you.. need to figure this out but not a priority for me yet. happy to take a PR in the meantime
