### ISSUE TITLE
Moving blog comments to Utterances

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#164]
Since I moved swyxkit to [use Github Issues as CMS](https://twitter.com/swyx/status/1480356418817753088) last year I also wrote my own Github `<Comments />` component. However there were subtle things that were buggy and the design didnt look all that good:

<p align="center">
<img src="https://user-images.githubusercontent.com/6764957/212504702-828ec2fb-d831-4857-ad0f-233365d92bcf.png" height=200 />
</p>

There's a well known project called [Utterances](https://github.com/utterance/utterances/) that pulls comments from github issues AND lets you login so that you can make comments right on the page. I know that this is mostly a better experience. So I decided to move it over:

<p align="center">
<img src="https://user-images.githubusercontent.com/6764957/212505291-1bca4373-d119-4b47-bf9c-fcf5bd97dadd.png" height=200 />
</p>

Compare side by side:

- old: https://63c3212a8ff96b0008153d81--swyxkit.netlify.app/moving-to-a-github-cms
- now: https://63c356b6a740bb0008e7a288--swyxkit.netlify.app/moving-to-a-github-cms

You can see the PR here #163. i mostly put it off for so long because i didnt quite get how to use utterances at first, but it took only a few mins of actually trying it to figure it out, and then to figure out how to add it to Sveltekit.

**Comment by sw-yx** [comment]
test post, this feels magical

**Comment by sw-yx** [comment]
note that utterances still has some rate limit issues... https://github.com/utterance/utterances/issues/640

![image](https://user-images.githubusercontent.com/6764957/212549237-a8840097-ad8d-4bee-a2f5-51e995153e3e.png)

**Comment by laymonage** [comment]
FYI there's also [giscus](https://github.com/giscus/giscus), similar to utterances but it's built on GitHub Discussions.

Disclaimer: I'm the author 😛

**Comment by sw-yx** [comment]
yes i did see it! however i already decided to centralize all my content + comments on issues rather than discussions. if you have that flexibility in future i'll explore switching

**Comment by sharu725** [comment]
What was the reason/s to choose issues over discussions?

**Comment by sw-yx** [comment]
honestly, just familiarity. at the time i had never used discussions and never used the API. it would probably work the same tbh.

**Comment by sharu725** [comment]
Also, **discussions** - online issues - isn't available by default. It should be enabled in repo settings.
