### ISSUE TITLE
try @svelte-put/toc for TOC instead

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#165]
#162 was a bust but @vnphanquang has [svelte-put.vnphanquang.com/docs/toc](https://t.co/aln2DKHTCr) which is promising

**Comment by janosh** [comment]
@vnphanquang Looks great! [Added to](https://github.com/janosh/awesome-sveltekit/commit/96fa42b) https://awesome-sveltekit.janosh.dev/svelte-put.

**Comment by vnphanquang** [comment]
Thanks @janosh, good collection you have there.
