### ISSUE TITLE
Issue with blog posts showing 404 messages

### ISSUE THREAD

**Issue by georgeoffley** [sw-yx/swyxkit#193]
I am still investigating, but I would like to know if anyone has seen the below error when going to one of the GitHub issues' pages.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/1258384/231859304-ca3ff0f1-3aee-422d-9ef0-9d6a09413930.png">

This results in the page throwing a 404 error and displaying the 404 page. I encountered this a couple of times before merging in all the new changes to the repo a couple of days ago, but I saw it start again after merging the updated main branch. 

I've confirmed that the API is pulling issues from GitHub, but that is as far as I've gotten.

**Comment by georgeoffley** [comment]
Narrowed down the issue to this code block [here](https://github.com/sw-yx/swyxkit/blob/6c84271913674be48320c489d7d790524586af4c/src/lib/content.js#L207). Something to do with the `mdsvex.compile()` function throwing an error. Continuing my investigation.

**Comment by sw-yx** [comment]
@georgeoffley would happily take PR for errors to fail properly when these things happen, this is one i havent been able to track down yet but yeah it does happen sometimes and is scary. 

shoudl also set up external monitoring eg ahrefs so you are notified of sudden spikes in 404s

**Comment by georgeoffley** [comment]
@sw-yx I started a branch to implement logging so we can start there. Just trying to make that as useful as possible.

**Comment by sw-yx** [comment]
ok!
