### ISSUE TITLE
Giscus

### ISSUE THREAD

**Issue by shinokada** [sw-yx/swyxkit#20]
Just a suggestion.
How about adding Giscus for comment to swyxkit.

[Giscus](https://github.com/giscus/giscus-component/tree/main/packages/svelte)

**Comment by sw-yx** [comment]
ooh interesting! i was also going to explore https://github.com/utterance as well

**Comment by shinokada** [comment]
That's a good one too.

**Comment by twhite96** [comment]
Yeah giscus is something I'm using on lots of sites. Similar to your implementation right out of the box.

**Comment by shinokada** [comment]
I created [svelte-utterances](https://svelte-utterances.vercel.app/).

Giscus didn't work for me. But a wrapper for utterances works well.

**Comment by sw-yx** [comment]
@shinokada if you are interested in PRing it feel free to do so! am not currently working on this at the moment but i dont mind so long as it is lightweight!
