### ISSUE TITLE
implement a "Storybook" component preview system, make sure it works with most design systems

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#21]
https://www.creative-tim.com/learning-lab/tailwind/svelte/overview/notus

talenote

**Comment by Ak4zh** [comment]
Should we implement [skeleton](https://github.com/Brain-Bones/skeleton) instead?

**Comment by sw-yx** [comment]
i think since i opened this issue there are other solutions to explore as well:

- https://vitebook.dev/
- https://github.com/leveluptuts/bookit
- https://github.com/histoire-dev/histoire/

i honestly havent tried them all so not sure what i would pick. let me know if you have a strong opinion, otherwise i am guessing that this is a tech choice i need to make myself

**Comment by ak4zh** [comment]
@sw-yx Ahh sorry I assumed it is about svelte component lib implementation.
I have never used StroryBook and any similar tech.
Looking forward to when it's get implemented on the repo, would be a good opportunity to finally learn one of those tech. :smile:

**Comment by sw-yx** [comment]
i made https://github.com/sw-yx/sveltekit-monorepo as a standalone repo today. man the tech is a bit messy and im not sure if its ready.

**Comment by ak4zh** [comment]
Looks cool.
Reading a lot about mono and turbo repos everywhere, but I haven't tried them yet on any of my projects.

Currently, I am creating a svelte kit SaaS template https://github.com/ak4zh/sveltekit-saas-starter, may be this will be a good time to try my hands on this tech to implement a frontend app, docs app etc. all in one SaaS template.

Need to research how to convert an existing repo to a turborepo.

**Comment by sw-yx** [comment]
implemented this for now https://github.com/sw-yx/swyxkit/pull/113 but the stories arent all written yet, pending improvements in the story writing DX

**Comment by sw-yx** [comment]
@ak4zh btw i have now set it up as #157
