### ISSUE TITLE
todo: tweet and youtube embeds

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#25]
lets make it easy to embed tweets and youtube in our blogposts!

grab code from 
https://github.com/sw-yx/swyxdotio/blob/0df79d5a86ebee31206c6220ab9d4f210281f271/src/lib/content.js#L99-L122

**Comment by twhite96** [comment]
Perhaps we could do something like this? Reducing JS is a good optimization, at least in my opinion.

May be a bit convoluted but I like the way it looks.

https://github.com/josephrexme/josephrex.me/blob/a8e385beab90e9d9305fcf331af6432986bdd5b2/lib/twitter.js

[blog post here](https://www.josephrex.me/ban-embed-codes/)

**Comment by sw-yx** [comment]
yes help welcome there :)
