### ISSUE TITLE
swyxkit.netlify.app articles not found

### ISSUE THREAD

**Issue by PH4NTOMiki** [sw-yx/swyxkit#35]
On your website swyxkit.netlify.app it appears that all the blog articles are returning 404s.

**Comment by sw-yx** [comment]
sorry that was a bad merge of #34 .. i have pinned my deploys for now while i figure out the error

**Comment by sw-yx** [comment]
i could not figure out the error - this is my debug log where i tried all the versions https://github.com/sveltejs/kit/issues/4079 but ran out of time to figure out the source of this

**Comment by sw-yx** [comment]
@PH4NTOMiki that was amazing help, thank you so much man, i was so frustrated by this error and turned out to be not our fault lol.
