### ISSUE TITLE
hello stackbit

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#36]
lorem ipsum

<script>
let x = 1
function foo() {
  x++
}
</script>

<button on:click={foo}>Count: {x}</button>

![image](https://user-images.githubusercontent.com/6764957/155363928-b1f8b971-1c26-4b20-ab72-0d260b9064d7.png?s=400&v=4)

sdlkjs

**Comment by sw-yx** [comment]
hello this is cool

```
let abc = 123
```

**Comment by rylandstackbit** [comment]
Hello word!
