### ISSUE TITLE
Mobile menu unresponsive

### ISSUE THREAD

**Issue by devrnt** [sw-yx/swyxkit#4]
The mobile menu is unresponsive on the `/about` page since no hydration has taken place (first visit). This is only on mobile/tablet screens (`@media (min-width: 768px) { ... }`). It's working as expected after visiting any other page.

Wondering how this can be tackled since `hydrate` is a page-level option, switching to a "css only" mobile nav seems the most obvious

**Comment by sw-yx** [comment]
appreciate the feedback.. havent figured this one out yet but will look at it when i have time

**Comment by sw-yx** [comment]
i ended up just disabling the hydration=false. sad day for perf but too lazy to code up css only mobile nav ha

the other thing i considered was hydrating the nav separately and mounting it on the layout.
