### ISSUE TITLE
Github CMS how should it work?

### ISSUE THREAD

**Issue by git-no** [sw-yx/swyxkit#50]
Interesting idea. I tried to understand the documentation on this site but I am missing:

### CMS Data

- The description says, as pull requests. But does this not interfere with pull requests on the source code?
- Why not storing the data in the code, e.g. in a dedicated data folder. Is the reason only the restricted number of API requests per hour?
- Is it possible to edit the content right in the syxkit web app (did not find a edit button)? I have installed the repo at Netlify but was not able to edit content. All the content in the web page is already hard coded in the svelte files.
 
### Personal Access Token
- Information what the personal access token should grant would be useful. Github offers a log of configuration of the PAT on the other hand it is a security risk. So I am asking me what flags should be enabled in the personal access token.

**Comment by sw-yx** [comment]
1. store data as issues, not PRs
2. no, its because github can host images. this method also doesnt cause a rebuild when you do minor changes to the content like i do all the time
3. no but you can code that yourself
4. none needed, just the default is fine!
