### ISSUE TITLE
Allowed posters are hard coded GitHub usernames

### ISSUE THREAD

**Issue by georgeoffley** [sw-yx/swyxkit#56]
Hey all!

I ran into an issue where any new GitHub issues I was adding to the repo I connected to the deployment were not showing up. I checked through the source and found a couple of things not mentioned in the guide. 

One issue that I don't think was mentioned was that Issues should have a `Published` label on GitHub for the logic to pick it up. Additionally, people need to update the `allowedPosters` array in `/src/lib/content.js` as right now, it is hardcoded to `sw-yx`.

I did submit a PR with a change to add the GH username to the `siteConfig.js` and import that into the `allowedPosters` array.

https://github.com/sw-yx/swyxkit/pull/55

I can also submit a PR to update the setup directions as well if that is something the maintainers would welcome.

**Comment by sw-yx** [comment]
PR please!

**Comment by georgeoffley** [comment]
> PR please!

Done, here!

https://github.com/sw-yx/swyxkit/pull/55
