### ISSUE TITLE
All blog pages return 404

### ISSUE THREAD

**Issue by Ak4zh** [sw-yx/swyxkit#75]
`/blog` returns 500 error code
All other blog articles returns 404 error code.

**Comment by sw-yx** [comment]
oh no :/ let me try to fix

**Comment by sw-yx** [comment]
issue is i let my github token expire 
![image](https://user-images.githubusercontent.com/6764957/176006993-fd617a17-7930-4eb1-a3d5-d38343ef3d5a.png)

**Comment by sw-yx** [comment]
fixed! thx. just make sure your github token doesnt expire
![image](https://user-images.githubusercontent.com/6764957/176007195-fe742fd6-f40e-4d89-b13d-4575e6eef8fa.png)
