### ISSUE TITLE
[Question] New posts does not appear after creating issue

### ISSUE THREAD

**Issue by Ak4zh** [sw-yx/swyxkit#76]
I followed all steps.
- Deployed to Netlify
- Added GH_TOKEN variable
- Created new [issue](https://github.com/Ak4zh/ak4zh-dot-com/issues/2) in the repo  and assigned the `Published` label

But the new posts does not appear in my [blog](https://ak4zh.com)

When I inspect the network requests I see followingf error when app blog tries to fetch blog contents:
`failed to load blogposts for some reason. check token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

Is there any specific permissions I need to enable while creating the Github Personal Access Token?

**Comment by sw-yx** [comment]
no, no specific permissions. not sure what else is missing tbh. let me know if you figure it out!

**Comment by sw-yx** [comment]
the issue may not be the token. look into the requests and the error stack for more details

**Comment by sw-yx** [comment]
reopen if still have a prblem!
