### ISSUE TITLE
better search

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#80]
---
title: Extremely lightweight fuzzy + highlighted search with @leeoniya/uFuzzy
slug: ufuzzy-search
category: Essay
description: Filters are clearly not the best user experience possible, yet the existing menu of options either involve a third party SaaS (Algolia), a running server (Typesense), network latency (Fuse.js on server) or clientside burden (Fuse.js on client). uFuzzy lets you do clientside fuzzy search with a bonus of highlighting results!
date: 2023-01-16
---

## 1min youtube short

{% youtube https://youtube.com/shorts/IPgfeH5Xams %}

## Context

I've wanted to add search to SwyxKit from day 1. Most developer blogs don't really have search, they have _filters_ - exact matching of lowercased substrings. That is not only the simplest implementation of search, it is also guaranteed to be the lightest-weight version of it in terms of clientside JS weight.  The most popular fuzzy search library in JS is Fuse.js, which weighs [15kb](https://bundlephobia.com/package/fuse.js@6.6.2) - not horrendous, but almost half as much as the rest of the JS i ship put together (33kb).

Filters are clearly not the best user experience possible, yet the existing menu of options either involve a third party SaaS (Algolia), a running server (Typesense), network latency (Fuse.js on server) or clientside burden (Fuse.js on client).

This changed for me as I learned about alternatives, for example https://github.com/kbrsh/wade which is 1kb but has no fuzzy search. The breakthrough came when @leeoniya posted [uFuzzy.js on Hacker News 3](https://news.ycombinator.com/item?id=33035580) months ago, with decent fuzzy search and only coming in at 4kb total size. 

I implemented it today and even a very naive implementation wasnt too bad
![image](https://user-images.githubusercontent.com/6764957/212566939-04fb8d95-ed4e-4d77-b695-e850c2987815.png)

You can see the PR in #169, but I'll describe the steps here.

## Making Hay

The first problem to encounter is that the uFuzzy docs offer cute API examples that only assume an array of strings, but most blog search comes in structured data of objects. I solved it by simple concat (as I later found [others also did](https://github.com/leeoniya/uFuzzy/issues/7)):

```js
// cleaned up code example
let haystack = rawdata.map(v => [v.title, v.subtitle, v.tags, v.content, v.description].join(' '))
let needle = 'foo' // search term;

let u = new uFuzzy();

let idxs = u.filter(haystack, needle);
let info = u.info(idxs, haystack, needle);
let order = u.sort(info, haystack, needle);

let searchResults = order.map(i => haystack[info.idx[order[i]]])
```

and this worked nicely enough.

## Highlighting results

uFuzzy also offers a `highlight` functionality, which is super cool. It involves inserting HTML into the text:

```js
// as before
let idxs = u.filter(haystack, needle);
let info = u.info(idxs, haystack, needle);
let order = u.sort(info, haystack, needle);

// highlighted search results
let searchResults = order.map(i => {
				const x = haystack[info.idx[order[i]]]
				const hl = uFuzzy.highlight(
					haystack[info.idx[order[i]]],
					info.ranges[order[i]],
					// marker function. add color for a bit of flair
					(part, matched) => matched ? '<b style="color:var(--brand-accent)">' + part + '</b>' : part;
				)
})
```

There are 3 small details to handle here:

1. I don't normally render the text as raw HTML, so I had to create a new path for rendering that HTML
2. while I want to render the added marker HTML, my text itself has some html entities that I _dont_ want to render
3. The marker just marks the part of the text, but doesnt do anything to help you truncate the long text to hone in on the marker

Solution

```svelte
<script>
// ...
let searchResults = order.map(i => {
	const x = haystack[info.idx[order[i]]]
	const hl = uFuzzy.highlight(
		haystack[info.idx[order[i]]]
		// replace html with same # of character whitespace as we dont actually want to render those html entities
		.replace("<", " ")
		.replace("/>", "  ")
		.replace(">", " "),
		info.ranges[order[i]],
		mark // mark function adds back the mark HTML we actually DO want to render
	)
	// nice slice surrounding the marked HTML
	.slice(Math.max(info.ranges[order[i]][0]-100,0), Math.min(info.ranges[order[i]][1]+100, haystack[info.idx[order[i]]].length));
	return {...x, highlightedResults: hl}
})

</script>

{#each searchResults as item}
	<li class="mb-8 text-lg">
			{#if item.highlightedResults}
				{@html item.highlightedResults}		
			{:else}
				{item.description}
			{/if}
	</li>
{/each}
```

This leads to a very nice search experience:
![image](https://user-images.githubusercontent.com/6764957/212567705-f89fec7f-add0-4d5f-8d67-00ed6f771e8f.png)

**Comment by sw-yx** [comment]
related #45

**Comment by sw-yx** [comment]
use this? https://github.com/leeoniya/uFuzzy

**Comment by sw-yx** [comment]
yeah this looks good https://github.com/leeoniya/uFuzzy/issues/7

**Comment by horacioh** [comment]
great post!

need to try a way to highlight HTML with different HTML tags. example if the needle is "between html" and I have the html below

```html
<p>how would highlight in between <b>html formats</b>
```

**Comment by sw-yx** [comment]
if you figure it out send in a PR :)

**Comment by Bishwas-py** [comment]
Awesome

**Comment by ohbob** [comment]
looks awesome and super fast!
