### ISSUE TITLE
Consider full content in RSS

### ISSUE THREAD

**Issue by bartveneman** [sw-yx/swyxkit#85]
Having the full blog post content in RSS allows readers to stay inside their RSS reader instead of having to switch to the website to read more.

**Comment by sw-yx** [comment]
PR welcome :)

**Comment by sw-yx** [comment]
will mark as wontfix for now but will consider a PR

**Comment by bartveneman** [comment]
Yeah, tried to get that PR going but got stuck on encoding stuff with that library that's being used. Perhaps another time.
