### ISSUE TITLE
Making 404 Pages useful

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#90]
When URLs break, 404 pages usually don't try to help you.

With https://github.com/sw-yx/swyxkit/pull/89, 404 pages in swyxkit will try to send you to the blog index to do a search based on the URL

![image](https://user-images.githubusercontent.com/6764957/185544677-2a9e9321-8bc1-41d4-bd2a-be7f1feb70b4.png)

we could also bring the search code into the 404 page, but that felt like too much work - let me know if you want to try doing that.

**Comment by mikhan** [comment]
Great idea! 👍
